info:
  name: ${spring.application.name}
  description: onboarding backend api
  version: 1.0.0

registry:
  adapter: dummy

strapi:
  base-url: http://localhost:1337/api

scorer:
  adapter: dummy

spectral:
  base-url: http://localhost:8081/api

jentic:
  base-url: http://localhost:8081/api

spring:
  application:
    name: api-onboarding
  mvc:
    problemdetails:
      enabled: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: false

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        'http.server.requests': true
        'resilience4j.circuitbreaker.calls': true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalArgumentException
    shared:
      slidingWindowSize: 100
      permittedNumberOfCallsInHalfOpenState: 30
      waitDurationInOpenState: 1s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
      ignoreExceptions:
        - java.lang.IllegalArgumentException
  instances:
    strapi:
      baseConfig: default

resilience4j.retry:
  configs:
    default:
      maxAttempts: 3
      waitDuration: 100
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - org.springframework.web.client.ResourceAccessException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
      ignoreExceptions:
        - java.lang.IllegalArgumentException
  instances:
    strapi:
      baseConfig: default
