### Valid overlaying request
POST http://{{host}}:{{port}}{{path}}/registrations/123/overlay
Content-Type: application/json

{
  "source": "file:///src/test/resources/e2e/test.overlay.yaml"
}

### Valid implementing request
PUT http://{{host}}:{{port}}{{path}}/registrations/123/component
Content-Type: application/json

{
  "name": "petstore",
  "revision": "1.0.0"
}

### Valid scoring request
PUT http://{{host}}:{{port}}{{path}}/registrations/123/score
Content-Type: application/json


### Valid on-boarding request
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/valid_candidate.openapi.yaml"
}

### Valid request - but missing non-required info
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/valid_candidate_missing_non_required_info.openapi.yaml"
}

### Invalid request - missing required info
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "file:///Users/olivier/Labor/github/my-api-portal/api-onboarding/src/test/resources/api/examples/invalid_candidate_missing_required_info.openapi.yaml"
}

### Valid request - but uri does not exist
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "file:///doesnotexist.openapi.yaml"
}

### Valid request - unexpected uri
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "d:/unexpected.openapi.yaml"
}

### Invalid request - uri is malformed - bad scheme
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "malformed_uri"
}

### Invalid request - uri is malformed - bad scheme
POST http://{{host}}:{{port}}{{path}}/registrations
Content-Type: application/json

{
  "source": "malformed_uri"
}

### Invalid request - operation not allowed
GET http://{{host}}:{{port}}{{path}}/registrations
