###
# @name valid candidate: 200
POST http://{{host}}:{{port}}{{path}}/scorings
Accept: application/json
Content-Type: application/json

{
  "source": "file:///valid_candidate.openapi.yaml",
  "contract": "OPENAPI"
}

###
# @name uri not found: 422
POST http://{{host}}:{{port}}{{path}}/scorings
Accept: application/json
Content-Type: application/json

{
  "source": "file:///notfound.openapi.yaml"
}
