/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a Candidate
         * @description Accepts a Candidate payload describing a specification source to be processed.
         */
        post: operations["submitCandidate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Score an existing specification resource
         * @description Actualises the score for an existing specification resource.
         */
        put: operations["scoreSpecification"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}/component": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Implement an existing specification resource
         * @description Assigns a component to an existing specification resource, effectively implementing it.
         */
        put: operations["implementSpecification"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/registrations/{id}/overlay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Overlay an existing specification resource
         * @description Applies an overlay to an existing specification resource which creates a new revision.
         */
        post: operations["overlaySpecification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Candidate: {
            /** @description Either an absolute URI to fetch the specification from, or the specification document itself. A single-line absolute URI is read as a location; anything else is read as the document. */
            source: string;
        };
        OverlayCandidate: {
            /**
             * Format: uri
             * @description URI pointing to the overlay document
             */
            source: string;
        };
        /** @description Response for accepted candidate submission */
        CandidateProcessed: {
            /** @description Unique identifier for the candidate */
            id?: string;
            /** @description Location the specification was fetched from; absent when it was submitted inline */
            source?: string;
            info: components["schemas"]["Info"];
            metadata?: components["schemas"]["Metadata"];
            contract: components["schemas"]["Contract"];
            status: components["schemas"]["Status"];
            scorecard?: components["schemas"]["Scorecard"];
            /** @description Detailed violations encountered during processing */
            violations?: components["schemas"]["Violation"][];
        };
        /** @description Basic information about the candidate */
        Info: {
            title: string;
            description: string;
            version: string;
        };
        /** @description Additional metadata about the candidate */
        Metadata: {
            name: string;
            revision: string;
            bundleName: string;
            productName: string;
            componentName?: string;
            componentRevision?: string;
        };
        /**
         * @description Specification contract version
         * @example OPENAPI_V31
         * @enum {string}
         */
        Contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
        /**
         * @description Current processing status
         * @enum {string}
         */
        Status: "IMPLEMENTED" | "PUBLISHED" | "REGISTERED" | "SCORED" | "VALID";
        /** @description Detailed scoring breakdown */
        Scorecard: {
            score: components["schemas"]["Score"];
            grade: components["schemas"]["Grade"];
            dimensions?: {
                /**
                 * @description Name of the scoring dimension
                 * @enum {string}
                 */
                name: "FC" | "SEC" | "DX" | "MR" | "ARAX" | "AU" | "AID";
                /** @description Intent of the scoring dimension */
                intent: string;
                score: components["schemas"]["Score"];
                grade: components["schemas"]["Grade"];
            }[];
            /** @description Detailed violations encountered during scoring */
            violations?: components["schemas"]["Violation"][];
        };
        /**
         * Format: int32
         * @description Overall quality score (0-100)
         */
        Score: number;
        /**
         * @description Overall quality grade based on score
         * @enum {string}
         */
        Grade: "A" | "A+" | "A-" | "B" | "B-" | "B-" | "C" | "C+" | "C-" | "D" | "D+" | "D-";
        /** @description Violation encountered during processing */
        Violation: {
            /** @description Code of violation */
            code: string;
            /** @description Description of violation */
            detail: string;
            /**
             * @description Severity of violation
             * @enum {string}
             */
            severity: "MAJOR" | "MINOR";
        };
        /** @description Component information for implementing a specification */
        Component: {
            /** @description Name of the component */
            name: string;
            /** @description Revision of the component */
            revision: string;
        };
        /** @description Response for successful overlay application */
        OverlayApplied: {
            /** @description Unique identifier for the overlaid specification */
            id: string;
        };
        /** @description An object to provide explicit details on a problem towards an API consumer. */
        ErrorDetail: {
            /** @description A granular description on the specific error related to a body property, query parameter, path parameters, and/or header. */
            detail: string;
            /** @description A JSON Pointer to a specific request body property that is the source of error. */
            pointer?: string;
            /** @description The name of the query or path parameter that is the source of error. */
            parameter?: string;
            /** @description The name of the header that is the source of error. */
            header?: string;
            /** @description A string containing additional provider specific codes to identify the error context. */
            code?: string;
        };
        /** @description An array of error details to accompany a problem details response. */
        Errors: components["schemas"]["ErrorDetail"][];
        ProblemDetails: {
            /**
             * Format: uri
             * @description A URI reference that identifies the problem type.
             */
            type?: string;
            /**
             * Format: int32
             * @description The HTTP status code generated by the origin server for this occurrence of the problem.
             */
            status?: number;
            /** @description A short, human-readable summary of the problem type. It should not change from occurrence to occurrence of the problem, except for purposes of localization. */
            title: string;
            /** @description A human-readable explanation specific to this occurrence of the problem. */
            detail?: string;
            /** @description A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced. */
            instance?: string;
            /** @description An API specific error code aiding the provider team understand the error based on their own potential taxonomy or registry. */
            code?: string;
            errors?: components["schemas"]["Errors"];
        };
    };
    responses: {
        /**
         * @description The request was malformed or could not be processed.
         *
         *     Examples of `Bad Request` problem detail responses:
         *
         *      - [Missing body property](https://problems-registry.smartbear.com/missing-body-property/)
         *      - [Invalid body property format](https://problems-registry.smartbear.com/invalid-body-property-format/)
         *      - [Invalid body property value](https://problems-registry.smartbear.com/invalid-body-property-value/)
         *      - [Missing request header](https://problems-registry.smartbear.com/missing-request-header/)
         *      - [Invalid request header format](https://problems-registry.smartbear.com/invalid-request-header-format/)
         *      - [Missing request parameter](https://problems-registry.smartbear.com/missing-request-parameter/)
         *      - [Invalid request parameter format](https://problems-registry.smartbear.com/invalid-request-parameter-format/)
         *      - [Invalid request parameter value](https://problems-registry.smartbear.com/invalid-request-parameter-value/)
         */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ProblemDetails"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submitCandidate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Candidate"];
            };
        };
        responses: {
            /** @description Ok — candidate has been validated, and scored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProcessed"];
                };
            };
            /** @description Ok — candidate has been validated, scored, and registered successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateProcessed"];
                };
            };
            /** @description The request was malformed or could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Your client issued a request that failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    scoreSpecification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of specification that needs to be updated */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ok — existing specification has been scored successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scorecard"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description Your client issued a request that failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    implementSpecification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of specification that needs to be implemented */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Component"];
            };
        };
        responses: {
            /** @description Ok — existing specification has been implemented successfully. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request was malformed or could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Your client issued a request that failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    overlaySpecification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ID of specification that needs to be overlaid */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayCandidate"];
            };
        };
        responses: {
            /** @description Ok — existing specification has been overlaid successfully. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverlayApplied"];
                };
            };
            /** @description The request was malformed or could not be processed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Your client issued a request that failed validation. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
}
