/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/specifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["specification/get/specifications"];
        put?: never;
        post: operations["specification/post/specifications"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/specifications/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["specification/get/specifications_by_id"];
        put: operations["specification/put/specifications_by_id"];
        post?: never;
        delete: operations["specification/delete/specifications_by_id"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "specification/get/specifications": {
        parameters: {
            query?: {
                fields?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                filters?: {
                    [key: string]: unknown;
                };
                _q?: string;
                sort?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                populate?: never[];
                status?: "draft" | "published";
                publicationFilter?: "never-published" | "has-published-version" | "modified" | "unmodified" | "never-published-document" | "has-published-version-document" | "published-without-draft" | "published-with-draft";
                hasPublishedVersion?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            documentId: string;
                            id: string;
                            specId: string;
                            name: string;
                            productName: string;
                            version: string;
                            revision: string;
                            bundleName: string;
                            componentName?: string;
                            componentRevision?: string;
                            /** @enum {string} */
                            contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                            body: unknown;
                            score?: unknown;
                            violations?: unknown;
                            createdAt?: string;
                            updatedAt?: string;
                            /** @default 2026-07-18T05:31:36.588Z */
                            publishedAt: string;
                        }[];
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "specification/post/specifications": {
        parameters: {
            query?: {
                fields?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                populate?: never[];
                status?: "draft" | "published";
                publicationFilter?: "never-published" | "has-published-version" | "modified" | "unmodified" | "never-published-document" | "has-published-version-document" | "published-without-draft" | "published-with-draft";
                hasPublishedVersion?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    data: {
                        specId: string;
                        name: string;
                        productName: string;
                        version: string;
                        revision: string;
                        bundleName: string;
                        componentName?: string;
                        componentRevision?: string;
                        /** @enum {string} */
                        contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                        body: unknown;
                        score?: unknown;
                        violations?: unknown;
                        /** @default 2026-07-18T05:31:37.015Z */
                        publishedAt: string;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            documentId: string;
                            id: string;
                            specId: string;
                            name: string;
                            productName: string;
                            version: string;
                            revision: string;
                            bundleName: string;
                            componentName?: string;
                            componentRevision?: string;
                            /** @enum {string} */
                            contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                            body: unknown;
                            score?: unknown;
                            violations?: unknown;
                            createdAt?: string;
                            updatedAt?: string;
                            /** @default 2026-07-18T05:31:36.602Z */
                            publishedAt: string;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "specification/get/specifications_by_id": {
        parameters: {
            query?: {
                fields?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                populate?: never[];
                filters?: {
                    [key: string]: unknown;
                };
                sort?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                status?: "draft" | "published";
                publicationFilter?: "never-published" | "has-published-version" | "modified" | "unmodified" | "never-published-document" | "has-published-version-document" | "published-without-draft" | "published-with-draft";
                hasPublishedVersion?: "true" | "false";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            documentId: string;
                            id: string;
                            specId: string;
                            name: string;
                            productName: string;
                            version: string;
                            revision: string;
                            bundleName: string;
                            componentName?: string;
                            componentRevision?: string;
                            /** @enum {string} */
                            contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                            body: unknown;
                            score?: unknown;
                            violations?: unknown;
                            createdAt?: string;
                            updatedAt?: string;
                            /** @default 2026-07-18T05:31:36.596Z */
                            publishedAt: string;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "specification/put/specifications_by_id": {
        parameters: {
            query?: {
                fields?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                populate?: never[];
                status?: "draft" | "published";
                publicationFilter?: "never-published" | "has-published-version" | "modified" | "unmodified" | "never-published-document" | "has-published-version-document" | "published-without-draft" | "published-with-draft";
                hasPublishedVersion?: "true" | "false";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    data: {
                        specId?: string;
                        name?: string;
                        productName?: string;
                        version?: string;
                        revision?: string;
                        bundleName?: string;
                        componentName?: string;
                        componentRevision?: string;
                        /** @enum {string} */
                        contract?: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                        body?: unknown;
                        score?: unknown;
                        violations?: unknown;
                        /** @default 2026-07-18T05:31:36.605Z */
                        publishedAt?: string;
                    };
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            documentId: string;
                            id: string;
                            specId: string;
                            name: string;
                            productName: string;
                            version: string;
                            revision: string;
                            bundleName: string;
                            componentName?: string;
                            componentRevision?: string;
                            /** @enum {string} */
                            contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                            body: unknown;
                            score?: unknown;
                            violations?: unknown;
                            createdAt?: string;
                            updatedAt?: string;
                            /** @default 2026-07-18T05:31:36.607Z */
                            publishedAt: string;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "specification/delete/specifications_by_id": {
        parameters: {
            query?: {
                fields?: ("specId" | "name" | "productName" | "version" | "revision" | "bundleName" | "componentName" | "componentRevision" | "contract" | "body" | "score" | "violations" | "createdAt" | "updatedAt" | "publishedAt")[];
                populate?: never[];
                filters?: {
                    [key: string]: unknown;
                };
                status?: "draft" | "published";
                publicationFilter?: "never-published" | "has-published-version" | "modified" | "unmodified" | "never-published-document" | "has-published-version-document" | "published-without-draft" | "published-with-draft";
                hasPublishedVersion?: "true" | "false";
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            documentId: string;
                            id: string;
                            specId: string;
                            name: string;
                            productName: string;
                            version: string;
                            revision: string;
                            bundleName: string;
                            componentName?: string;
                            componentRevision?: string;
                            /** @enum {string} */
                            contract: "OPENAPI_V30" | "OPENAPI_V31" | "OPENAPI_V32" | "ASYNCAPI_V2" | "ASYNCAPI_V3" | "GRAPHQLS" | "WSDL_V11" | "WSDL_V20" | "OVERLAY_V10" | "OVERLAY_V11";
                            body: unknown;
                            score?: unknown;
                            violations?: unknown;
                            createdAt?: string;
                            updatedAt?: string;
                            /** @default 2026-07-18T05:31:36.609Z */
                            publishedAt: string;
                        };
                    };
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
